// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPmPNL74h-tTp-J2HRhaFv6A2AyB8EG4',
    appId: '1:149482148378:web:a7674dd026e14b8a35b7a3',
    messagingSenderId: '149482148378',
    projectId: 'coffe-reference',
    authDomain: 'coffe-reference.firebaseapp.com',
    storageBucket: 'coffe-reference.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-uVP-zVJh73xN31JxbVSqHX958iMv_E',
    appId: '1:149482148378:android:2516e9becf73ccaf35b7a3',
    messagingSenderId: '149482148378',
    projectId: 'coffe-reference',
    storageBucket: 'coffe-reference.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nhxXUH5tF6zooIfvPlF35cIOwZxcKfc',
    appId: '1:149482148378:ios:cbe442da051ac2ff35b7a3',
    messagingSenderId: '149482148378',
    projectId: 'coffe-reference',
    storageBucket: 'coffe-reference.appspot.com',
    iosBundleId: 'com.example.coffeReference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nhxXUH5tF6zooIfvPlF35cIOwZxcKfc',
    appId: '1:149482148378:ios:40ff724a0c71f6be35b7a3',
    messagingSenderId: '149482148378',
    projectId: 'coffe-reference',
    storageBucket: 'coffe-reference.appspot.com',
    iosBundleId: 'com.example.coffeReference.RunnerTests',
  );
}
