// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHH75dkMWFY4bXXMFJ1W-gsgX7ml18No',
    appId: '1:888798613444:web:1e11b22c5872d5178d5e91',
    messagingSenderId: '888798613444',
    projectId: 'coffe-demo-aec39',
    authDomain: 'coffe-demo-aec39.firebaseapp.com',
    storageBucket: 'coffe-demo-aec39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bqpWQpOIf6L_lbxJduC6QMDIZ7xqRYc',
    appId: '1:888798613444:android:04943f7833101f668d5e91',
    messagingSenderId: '888798613444',
    projectId: 'coffe-demo-aec39',
    storageBucket: 'coffe-demo-aec39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKid_cKAwQDoGeqP7oypO2O5ogn1DF1MI',
    appId: '1:888798613444:ios:b349a579edcdcf8d8d5e91',
    messagingSenderId: '888798613444',
    projectId: 'coffe-demo-aec39',
    storageBucket: 'coffe-demo-aec39.appspot.com',
    iosBundleId: 'com.example.coffeDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKid_cKAwQDoGeqP7oypO2O5ogn1DF1MI',
    appId: '1:888798613444:ios:d1edab10e8086d268d5e91',
    messagingSenderId: '888798613444',
    projectId: 'coffe-demo-aec39',
    storageBucket: 'coffe-demo-aec39.appspot.com',
    iosBundleId: 'com.example.coffeDemo.RunnerTests',
  );
}
